const { app, BrowserWindow, ipcMain, shell, dialog } = require('electron');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');
const { spawn, execFileSync } = require('child_process');
const { Client } = require('minecraft-launcher-core');
const { scanModpacks, auditResourcePacks } = require('./modpack-manager');

const RUNTIME_DIR = path.join(app.getPath('userData'), 'runtime');
const JAVA_DIR = path.join(RUNTIME_DIR, 'jdk17');
const JAVA_ZIP = path.join(RUNTIME_DIR, 'jdk17.zip');
const DEFAULT_MANIFEST = path.join(__dirname, '..', 'modpack', 'manifest.json');
const FABRIC_INSTALLER = 'https://maven.fabricmc.net/net/fabricmc/fabric-installer/1.0.3/fabric-installer-1.0.3.jar';
const JAVA_URL = 'https://api.adoptium.net/v3/binary/latest/17/ga/windows/x64/jdk/hotspot/normal/eclipse';
let GAME_DIR = path.join(app.getPath('userData'), 'minecraft');
let MANIFEST_PATH = DEFAULT_MANIFEST;
let INSTALLED_MANIFEST = path.join(GAME_DIR, 'novus-manifest.json');
let selectedPack = null, win = null, gameProcess = null, launchInProgress = false;
const send = (event, payload) => { if (win && !win.isDestroyed()) win.webContents.send(event, payload); };
function createWindow(){win=new BrowserWindow({width:1280,height:820,minWidth:1000,minHeight:680,backgroundColor:'#f7f7f6',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.loadFile(path.join(__dirname,'renderer','index.html'));}
function readManifest(){if(!fs.existsSync(MANIFEST_PATH))throw new Error(`manifest.json introuvable : ${MANIFEST_PATH}`);return JSON.parse(fs.readFileSync(MANIFEST_PATH,'utf8'));}
function sha256(file){return new Promise((resolve,reject)=>{const h=crypto.createHash('sha256'),s=fs.createReadStream(file);s.on('error',reject);s.on('data',d=>h.update(d));s.on('end',()=>resolve(h.digest('hex')));});}
async function download(url,dest,label,expected){fs.mkdirSync(path.dirname(dest),{recursive:true});if(fs.existsSync(dest)&&expected){try{if((await sha256(dest)).toLowerCase()===expected.toLowerCase())return false;}catch(_){}fs.rmSync(dest,{force:true});}send('status',{text:`Téléchargement : ${label}`});const r=await fetch(url,{redirect:'follow',headers:{'User-Agent':'Novus-Launcher/1.3'}});if(!r.ok)throw new Error(`${label} : téléchargement impossible (${r.status})`);fs.writeFileSync(dest,Buffer.from(await r.arrayBuffer()));if(expected&&(await sha256(dest)).toLowerCase()!==expected.toLowerCase()){fs.rmSync(dest,{force:true});throw new Error(`Hash SHA-256 invalide pour ${label}.`);}return true;}
function fabricId(m){return `fabric-loader-${m.fabricLoader}-${m.minecraft}`;} function fabricJson(m){const id=fabricId(m);return path.join(GAME_DIR,'versions',id,`${id}.json`);}
function javaVersion(java){try{return String(execFileSync(java,['-version'],{encoding:'utf8',stdio:['ignore','pipe','pipe']}));}catch(e){return `${e.stderr||''}${e.stdout||''}`;}}
function isJava17(java){return /version\s+"17(?:[.\-]|$)/.test(javaVersion(java));}
function findJava(){const c=[];if(process.env.JAVA_HOME)c.push(path.join(process.env.JAVA_HOME,'bin','java.exe'));if(process.env.ProgramFiles){c.push(path.join(process.env.ProgramFiles,'Java','jdk-17','bin','java.exe'));c.push(path.join(process.env.ProgramFiles,'Eclipse Adoptium','jdk-17','bin','java.exe'));}c.push(path.join(JAVA_DIR,'bin','java.exe'),'java.exe');for(const x of c){try{if(isJava17(x))return x;}catch(_){}}return null;}
async function installJava17(){const found=findJava();if(found)return found;if(process.platform!=='win32')throw new Error('Java 17 automatique est disponible sur Windows uniquement.');fs.mkdirSync(RUNTIME_DIR,{recursive:true});send('status',{text:'Java 17 x64 absent : téléchargement automatique...'});await download(JAVA_URL,JAVA_ZIP,'Java 17 x64');if(fs.existsSync(JAVA_DIR))fs.rmSync(JAVA_DIR,{recursive:true,force:true});fs.mkdirSync(JAVA_DIR,{recursive:true});await new Promise((resolve,reject)=>{const cmd=`Expand-Archive -LiteralPath '${JAVA_ZIP.replace(/'/g,"''")}' -DestinationPath '${JAVA_DIR.replace(/'/g,"''")}' -Force`;const p=spawn('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',cmd],{windowsHide:true});let err='';p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',c=>c===0?resolve():reject(new Error(`Extraction Java échouée (${c}) ${err}`)));});let java=null;function walk(dir,d=0){if(java||d>5)return;let es;try{es=fs.readdirSync(dir,{withFileTypes:true});}catch(_){return;}for(const e of es){const f=path.join(dir,e.name);if(e.isFile()&&e.name.toLowerCase()==='java.exe'&&f.toLowerCase().endsWith(`${path.sep}bin${path.sep}java.exe`)){java=f;return;}if(e.isDirectory())walk(f,d+1);}}walk(JAVA_DIR);try{fs.rmSync(JAVA_ZIP,{force:true});}catch(_){}if(!java||!isJava17(java))throw new Error('Java 17 x64 a été téléchargé mais n’a pas pu être initialisé.');return java;}
async function installFabric(m){if(fs.existsSync(fabricJson(m)))return;const java=await installJava17(),installer=path.join(GAME_DIR,'fabric-installer.jar');await download(FABRIC_INSTALLER,installer,'Fabric Installer');await new Promise((resolve,reject)=>{const p=spawn(java,['-jar',installer,'client','-dir',GAME_DIR,'-mcversion',m.minecraft,'-loader',m.fabricLoader,'-noprofile','-downloadMinecraft'],{windowsHide:true,cwd:GAME_DIR});let err='';p.stderr.on('data',d=>err+=d);p.stdout.on('data',d=>{const t=d.toString().trim();if(t)send('status',{text:t.split(/\r?\n/).filter(Boolean).pop()});});p.on('error',reject);p.on('close',c=>c===0?resolve():reject(new Error(`Installation Fabric échouée (${c}). ${err.trim()}`)));});try{fs.rmSync(installer,{force:true});}catch(_){}if(!fs.existsSync(fabricJson(m)))throw new Error(`Fabric incomplet : ${fabricId(m)}.`);}
async function getMod(mod,m){const u=new URL(`https://api.modrinth.com/v2/project/${encodeURIComponent(mod.project)}/version`);u.searchParams.set('loaders',JSON.stringify(['fabric']));u.searchParams.set('game_versions',JSON.stringify([m.minecraft]));u.searchParams.set('version_type','release');const r=await fetch(u,{headers:{'User-Agent':'Novus-Launcher/1.3'}});if(!r.ok)throw new Error(`Modrinth : ${mod.name} (${r.status})`);const vs=await r.json();if(!vs.length)throw new Error(`Aucune version compatible de ${mod.name}.`);const v=vs[0],f=v.files?.find(x=>x.primary)||v.files?.[0];if(!f?.url||!f?.filename)throw new Error(`Fichier de ${mod.name} introuvable.`);return{v,f};}
async function installMod(mod,m){const {v,f}=await getMod(mod,m),filename=path.basename(f.filename);await download(f.url,path.join(GAME_DIR,'mods',filename),`${mod.name} ${v.version_number}`,f.hashes?.sha256);return{...mod,filename,version:v.version_number,sha256:f.hashes?.sha256||null};}
function installed(){try{return fs.existsSync(INSTALLED_MANIFEST)?JSON.parse(fs.readFileSync(INSTALLED_MANIFEST,'utf8')):null;}catch(_){return null;}}
async function verifyMods(m){const dir=path.join(GAME_DIR,'mods');fs.mkdirSync(dir,{recursive:true});const i=installed(),required=m.mods||[],missing=[];for(const mod of required){const old=(i?.installedMods||[]).find(x=>x.project===mod.project),file=old?.filename&&path.join(dir,old.filename);if(!file||!fs.existsSync(file)||(old.sha256&&(await sha256(file)).toLowerCase()!==old.sha256.toLowerCase()))missing.push(mod);}for(let n=0;n<missing.length;n++){await installMod(missing[n],m);send('progress',{percent:30+Math.round((n+1)/missing.length*45),phase:`${missing[n].name} vérifié`});}const keep=new Set(required.map(x=>x.project));for(const old of i?.installedMods||[]){if(old.project&&!keep.has(old.project)&&old.filename){const f=path.join(dir,old.filename);if(fs.existsSync(f))fs.rmSync(f,{force:true});}}return fs.readdirSync(dir).filter(x=>x.toLowerCase().endsWith('.jar'));}
async function copyLocalMods(m){const source=path.join(path.dirname(MANIFEST_PATH),'mods'),target=path.join(GAME_DIR,'mods');fs.mkdirSync(target,{recursive:true});if(!fs.existsSync(source))return[];const out=[];for(const e of fs.readdirSync(source,{withFileTypes:true})){if(!e.isFile()||!e.name.toLowerCase().endsWith('.jar'))continue;const src=path.join(source,e.name),dst=path.join(target,path.basename(e.name));fs.copyFileSync(src,dst);out.push(e.name);}return out;}
async function install(){const m=readManifest();fs.mkdirSync(GAME_DIR,{recursive:true});send('progress',{percent:2,phase:`Préparation de ${m.name||'Novus'}`});await installJava17();await installFabric(m);const mods=[];for(let n=0;n<(m.mods||[]).length;n++){mods.push(await installMod(m.mods[n],m));send('progress',{percent:30+Math.round((n+1)/Math.max(1,m.mods.length)*45),phase:`${m.mods[n].name} installé`});}const localMods=await copyLocalMods(m);for(const f of m.files||[]){const root=path.resolve(GAME_DIR),target=path.resolve(GAME_DIR,f.path);if(!target.startsWith(root+path.sep))throw new Error(`Chemin interdit : ${f.path}`);await download(f.url,target,f.path,f.sha256);}fs.writeFileSync(INSTALLED_MANIFEST,JSON.stringify({...m,installedAt:new Date().toISOString(),installedMods:mods,localMods},null,2));send('installed',{installed:true,gameDir:GAME_DIR,mods,localMods});send('progress',{percent:100,phase:'Installation terminée'});return{ok:true,gameDir:GAME_DIR,mods,localMods};}
async function ensureReady(m){fs.mkdirSync(GAME_DIR,{recursive:true});const i=installed();if(!i||i.version!==m.version||i.minecraft!==m.minecraft||i.fabricLoader!==m.fabricLoader||!fs.existsSync(fabricJson(m)))await install();await installFabric(m);await verifyMods(m);await copyLocalMods(m);}
function auth(name='NovusPlayer'){return{access_token:'0',client_token:crypto.randomUUID(),uuid:crypto.createHash('md5').update(`OfflinePlayer:${name}`).digest('hex'),name,user_properties:'{}',meta:{type:'mojang'}};}
async function launch(server){const m=readManifest();if(launchInProgress||gameProcess)throw new Error('Minecraft est déjà en cours de lancement ou déjà lancé.');await ensureReady(m);const java=await installJava17(),launcher=new Client();launchInProgress=true;launcher.on('debug',x=>send('game-log',{text:`[MCLC] ${x}`}));launcher.on('data',x=>send('game-log',{text:String(x)}));launcher.on('arguments',x=>send('game-log',{text:`[MCLC] Arguments : ${Array.isArray(x)?x.join(' '):x}`}));launcher.on('download-status',x=>send('game-progress',x));launcher.on('error',e=>send('game-error',{message:e?.stack||e?.message||String(e)}));launcher.on('close',code=>{gameProcess=null;launchInProgress=false;send('game-exit',{code});});const o={authorization:auth(m.playerName||'NovusPlayer'),root:GAME_DIR,version:{number:m.minecraft,type:'release',custom:fabricId(m)},memory:{max:m.memoryMax||'4G',min:m.memoryMin||'2G'},javaPath:java};const s=server?.host?server:m.server;if(s?.host)o.server={host:String(s.host),port:Number(s.port||25565)};send('status',{text:'Lancement de Novus...'});try{const p=await launcher.launch(o);if(!p||typeof p.on!=='function')throw new Error('Minecraft n’a pas retourné de processus.');gameProcess=p;launchInProgress=false;p.on('error',e=>send('game-error',{message:e.message}));p.on('exit',(code,signal)=>send('game-log',{text:`[NOVUS] Processus terminé : ${code} ${signal||''}`}));send('game-started',{started:true,pid:p.pid||null});send('status',{text:'Minecraft est lancé.'});return{ok:true,pid:p.pid||null};}catch(e){gameProcess=null;launchInProgress=false;throw e;}}
function bases(){const a=process.env.APPDATA||'';return[{path:path.join(a,'novus-launcher','modpacks'),source:'Novus / modpacks',recursive:true},{path:path.join(a,'novus-launcher','modpack'),source:'Novus / modpack',recursive:true},{path:path.join(process.cwd(),'modpacks'),source:'Launcher / modpacks',recursive:true},{path:path.join(process.cwd(),'modpack'),source:'Launcher / modpack',recursive:true},{path:path.join(__dirname,'..','modpacks'),source:'Application / modpacks',recursive:true},{path:path.join(__dirname,'..','modpack'),source:'Application / modpack',recursive:true}];}
ipcMain.handle('get-modpacks',()=>scanModpacks(bases()));
ipcMain.handle('select-modpack',(_e,pack)=>{try{const found=scanModpacks(bases()).find(p=>path.resolve(p.directory).toLowerCase()===path.resolve(pack.directory).toLowerCase());if(!found)throw new Error('Modpack non détecté.');selectedPack=found;MANIFEST_PATH=found.manifestPath;GAME_DIR=path.join(app.getPath('userData'),'minecraft',found.id);INSTALLED_MANIFEST=path.join(GAME_DIR,'novus-manifest.json');const m=readManifest();return{ok:true,pack:found,manifest:m,gameDir:GAME_DIR,installed:Boolean(installed()&&fs.existsSync(fabricJson(m)))};}catch(e){return{ok:false,error:e.message};}});
ipcMain.handle('get-info',()=>{const m=readManifest(),i=installed(),d=path.join(GAME_DIR,'mods');return{name:m.name,version:m.version,minecraft:m.minecraft,loader:m.loader,fabricLoader:m.fabricLoader,gameDir:GAME_DIR,installed:Boolean(i&&fs.existsSync(fabricJson(m))),mods:m.mods||[],detectedMods:fs.existsSync(d)?fs.readdirSync(d).filter(x=>x.toLowerCase().endsWith('.jar')):[],server:m.server||{},selectedPack};});
ipcMain.handle('add-local-mod',async()=>{if(!selectedPack)throw new Error('Sélectionne d’abord un modpack.');const result=await dialog.showOpenDialog(win,{title:'Ajouter des mods à Novus',properties:['openFile','multiSelections'],filters:[{name:'Mods Minecraft',extensions:['jar']}]});if(result.canceled)return{ok:false,canceled:true};const dir=path.join(path.dirname(MANIFEST_PATH),'mods');fs.mkdirSync(dir,{recursive:true});const added=[];for(const file of result.filePaths){const name=path.basename(file);fs.copyFileSync(file,path.join(dir,name));added.push(name);}return{ok:true,added,security:auditResourcePacks(path.dirname(MANIFEST_PATH),GAME_DIR)};});
ipcMain.handle('security-audit',()=>{if(!selectedPack)throw new Error('Sélectionne un modpack.');return auditResourcePacks(selectedPack.directory,GAME_DIR);});
ipcMain.handle('install',async()=>{try{return await install();}catch(e){send('error',{message:e.stack||e.message});return{ok:false,error:e.message};}});
ipcMain.handle('launch',async(_e,s)=>{try{return await launch(s);}catch(e){send('error',{message:e.stack||e.message});return{ok:false,error:e.message};}});
ipcMain.handle('open-game-dir',()=>{shell.openPath(GAME_DIR);return GAME_DIR;});
app.whenReady().then(createWindow);app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});
