const $ = id => document.getElementById(id);
const pages = { home:'ACCUEIL', modpack:'MODPACK', server:'SERVEUR', settings:'PARAMÈTRES' };
let info = null;
let discoveredPacks = [];
let selectedPack = null;

function setStatus(text,error=false){$('status').textContent=text;$('status').classList.toggle('status-error',error);}
function setProgress(percent,phase){const v=Math.max(0,Math.min(100,Number(percent)||0));$('bar').style.width=`${v}%`;$('percent').textContent=`${v}%`;if(phase)$('phase').textContent=phase;}
function setButtons(busy){$('play').disabled=busy||!info?.installed;$('install').disabled=busy;$('modInstall').disabled=busy;$('playServer').disabled=busy||!info?.installed;}
function pathEquals(a,b){return !!a&&!!b&&String(a).replaceAll('\\','/').toLowerCase()===String(b).replaceAll('\\','/').toLowerCase();}
function renderMods(){const list=$('modList');list.innerHTML='';for(const mod of info?.mods||[]){const row=document.createElement('div');row.className='mod-row';const icon=document.createElement('div');icon.className='mod-icon';icon.textContent='◆';const body=document.createElement('div');const name=document.createElement('strong');name.textContent=mod.name||mod.project||'Mod';const meta=document.createElement('small');meta.textContent=`Fabric • Minecraft ${info.minecraft}`;body.append(name,meta);const ok=document.createElement('span');ok.className='mod-ok';ok.textContent='AUTO';row.append(icon,body,ok);list.appendChild(row);}}
function renderPackDiscovery(){const list=$('packList');list.innerHTML='';$('packCount').textContent=`${discoveredPacks.length} modpack${discoveredPacks.length>1?'s':''} détecté${discoveredPacks.length>1?'s':''}`;if(!discoveredPacks.length){const e=document.createElement('div');e.className='pack-empty';e.textContent='Aucun modpack trouvé.';list.appendChild(e);return;}for(const pack of discoveredPacks){const card=document.createElement('article');card.className='pack-card';if(selectedPack&&pathEquals(pack.directory,selectedPack.directory))card.classList.add('current-pack');card.addEventListener('click',()=>selectPack(pack));const icon=document.createElement('div');icon.className='pack-icon';icon.textContent='N';const body=document.createElement('div');body.className='pack-card-body';const title=document.createElement('strong');title.textContent=pack.name;const version=document.createElement('small');version.textContent=`v${pack.version} • Minecraft ${pack.minecraft} • ${pack.loader}${pack.fabricLoader?' '+pack.fabricLoader:''}`;const source=document.createElement('span');source.textContent=`${pack.mods} mod${pack.mods>1?'s':''} • ${pack.source}`;body.append(title,version,source);const badge=document.createElement('b');badge.textContent=selectedPack&&pathEquals(pack.directory,selectedPack.directory)?'SÉLECTIONNÉ':'SÉLECTIONNER';card.append(icon,body,badge);list.appendChild(card);}}
async function refreshPacks(){try{discoveredPacks=await window.novus.getModpacks();if(selectedPack){const same=discoveredPacks.find(p=>pathEquals(p.directory,selectedPack.directory));if(same)selectedPack=same;}renderPackDiscovery();}catch(e){discoveredPacks=[];renderPackDiscovery();}}
async function selectPack(pack){if(selectedPack&&pathEquals(pack.directory,selectedPack.directory))return;setStatus(`Sélection de ${pack.name}...`);const result=await window.novus.selectModpack(pack);if(!result.ok){setStatus(`Échec : ${result.error}`,true);return;}selectedPack=result.pack;info=await window.novus.getInfo();$('packName').textContent=info.name;$('version').textContent=info.version;$('packVersion').textContent=info.version;$('details').textContent=`Minecraft ${info.minecraft} • ${info.loader} ${info.fabricLoader||''} • ${info.mods.length} mods`;$('packCardTitle').textContent=`${info.loader||'Fabric'}${info.mods.length?` • ${info.mods.length} mods`:''}`;$('gameDir').textContent=info.gameDir;loadServerFields();renderMods();setButtons(false);renderPackDiscovery();setStatus(info.installed?'Prêt à jouer':'Prêt à installer');$('phase').textContent=info.installed?'Modpack installé et vérifié.':'Ce modpack doit être installé.';}
function loadServerFields(){const s=info?.server||{};$('serverInputName').value=s.name||'Novus Modded';$('serverInputHost').value=s.host||'';$('serverInputPort').value=s.port||25565;$('serverName').textContent=s.name||'Novus Modded';$('serverHost').textContent=s.host||'Serveur à configurer';$('serverPort').textContent=s.port||25565;$('serverBadge').textContent=s.host?'CONFIGURÉ':'À CONFIGURER';}
async function refresh(){info=await window.novus.getInfo();selectedPack=info.selectedPack||selectedPack;$('packName').textContent=info.name;$('version').textContent=info.version;$('packVersion').textContent=info.version;$('details').textContent=`Minecraft ${info.minecraft} • ${info.loader} ${info.fabricLoader||''} • ${info.mods.length} mods`;$('packCardTitle').textContent=`${info.loader||'Fabric'}${info.mods.length?` • ${info.mods.length} mods`:''}`;$('gameDir').textContent=info.gameDir;$('accountName').textContent=localStorage.getItem('novusPlayer')||'Novus Player';$('playerName').value=localStorage.getItem('novusPlayer')||'NovusPlayer';$('memoryMax').value=localStorage.getItem('novusMemoryMax')||'4G';$('memoryMin').value=localStorage.getItem('novusMemoryMin')||'2G';loadServerFields();renderMods();setButtons(false);setStatus(info.installed?'Prêt à jouer':'Prêt à installer');$('phase').textContent=info.installed?'Modpack installé et vérifié.':'Installe Minecraft, Fabric et les mods.';}
async function doInstall(){setButtons(true);setProgress(0,'Préparation...');setStatus('Installation en cours...');const r=await window.novus.install();if(r.ok){setProgress(100,'Installation terminée');await refresh();await refreshPacks();}else{setStatus(`Échec : ${r.error}`,true);setButtons(false);}}
async function play(server=null){setButtons(true);setStatus(server?'Connexion au serveur...':'Lancement de Novus...');const r=await window.novus.launch(server);if(!r.ok){setStatus(`Échec : ${r.error}`,true);setButtons(false);}}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active-page'));$(`page-${b.dataset.page}`).classList.add('active-page');$('crumb').textContent=pages[b.dataset.page];}));
$('install').addEventListener('click',doInstall);$('modInstall').addEventListener('click',doInstall);$('play').addEventListener('click',()=>play());$('openDir').addEventListener('click',()=>window.novus.openGameDir());$('refreshPacks').addEventListener('click',refreshPacks);$('saveServer').addEventListener('click',()=>{const host=$('serverInputHost').value.trim(),port=Number($('serverInputPort').value);if(!host){$('serverMessage').textContent='Entre une adresse de serveur.';return;}if(!port||port<1||port>65535){$('serverMessage').textContent='Port invalide.';return;}localStorage.setItem('novusServer',JSON.stringify({name:$('serverInputName').value.trim()||'Novus Modded',host,port}));info.server={name:$('serverInputName').value.trim()||'Novus Modded',host,port};loadServerFields();$('serverMessage').textContent='Serveur enregistré.';});$('playServer').addEventListener('click',()=>{const host=$('serverInputHost').value.trim(),port=Number($('serverInputPort').value);if(host)play({host,port});else $('serverMessage').textContent='Configure le serveur avant de jouer.';});$('saveSettings').addEventListener('click',()=>{const n=$('playerName').value.trim()||'NovusPlayer';localStorage.setItem('novusPlayer',n);localStorage.setItem('novusMemoryMax',$('memoryMax').value.trim()||'4G');localStorage.setItem('novusMemoryMin',$('memoryMin').value.trim()||'2G');$('accountName').textContent=n;setStatus('Paramètres enregistrés');});window.novus.onStatus(d=>setStatus(d.text));window.novus.onProgress(d=>setProgress(d.percent,d.phase));window.novus.onInstalled(()=>refresh());window.novus.onError(d=>{setStatus(`Erreur : ${d.message}`,true);setButtons(false);});window.novus.onGameError(d=>{setStatus(`Minecraft : ${d.message}`,true);setButtons(false);});window.novus.onGameExit(d=>{setStatus(`Minecraft fermé (${d.code??0})`);setButtons(false);});Promise.all([refresh(),refreshPacks()]).catch(e=>setStatus(`Erreur : ${e.message}`,true));
